I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 47, in script
    volume music "0.3"
Exception: Sayer 'volume' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 47, in script
    volume music "0.3"
  File "C:\Users\Stefan Jan\Desktop\test\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Stefan Jan\Desktop\test\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'volume' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Max Life 0.1
Sun Aug 30 02:23:36 2020
